<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

define('THANH_PHO', 'THANH_PHO');

define('GIAN_GIAO', 'GIAN_GIAO');
define('ADDITIONAL_INFO_MUA_VTH', 'ADDITIONAL_INFO_MUA_VTH');
define('ADDITIONAL_INFO_MUA_VTH_500KG', 'ADDITIONAL_INFO_MUA_VTH_500KG');
define('ADDITIONAL_INFO_MUA_VTH_1000KG', 'ADDITIONAL_INFO_MUA_VTH_1000KG');
define('PHAN_TRAM_THEO_THANG_THUE', 'PHAN_TRAM_THEO_THANG_THUE');

// BÁN VTH
define('BAN_VTH_1000KG_TRONG_TPHCM', 'BAN_VTH_1000KG_TRONG_TPHCM');
define('BAN_VTH_1000KG_NGOAI_TPHCM', 'BAN_VTH_1000KG_NGOAI_TPHCM');
define('BAN_VTH_500KG_TRONG_TPHCM', 'BAN_VTH_500KG_TRONG_TPHCM');
define('BAN_VTH_500KG_NGOAI_TPHCM', 'BAN_VTH_500KG_NGOAI_TPHCM');

// THUÊ VTH
define('THUE_VTH_500KG_TRONG_TPHCM', 'THUE_VTH_500KG_TRONG_TPHCM');
define('THUE_VTH_500KG_NGOAI_TPHCM', 'THUE_VTH_500KG_NGOAI_TPHCM');
define('THUE_VTH_1000KG_TRONG_TPHCM', 'THUE_VTH_1000KG_TRONG_TPHCM');
define('THUE_VTH_1000KG_NGOAI_TPHCM', 'THUE_VTH_1000KG_NGOAI_TPHCM');

define('PHI_VAN_CHUYEN_GIAN_GIAO', 'PHI_VAN_CHUYEN_GIAN_GIAO');

//GIÁ TRỊ SẢN PHẨM
define('GIA_TRI_SAN_PHAM', 'GIA_TRI_SAN_PHAM');